[book]
authors = ["Azriel Hoh"]
language = "en"
multilingual = false
src = "src"
title = "mdbook Line Numbers Demo"

[output.html]
additional-js = ["js/highlightjs-line-numbers.js"]

[output.html.code.hidelines]
python = "~"
