on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

name: Book

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install `mdbook`
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: latest

      - run: mdbook build

      - name: Setup Pages
        uses: actions/configure-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          path: 'book'

      - name: Deploy to GitHub Pages
        id: deployment
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/deploy-pages@v2
